### ISSUE TITLE
Demo with Moveable

### ISSUE THREAD

**Issue by DavidTschan** [daybrush/selecto#1]
## Environments
* Framework name: React
* Framework version: 16.13.1
* Component name: Selecto
* Component version: 1.0.0
* Testable Address(optional): 

## Description
Hello I was wondering if you could provide examples of Selecto together with Moveable (especially resizable). Thank you for all your great work.

**Comment by daybrush** [comment]
@DavidTschan 

Check this link:
https://daybrush.com/selecto/storybook/?path=/story/selecto-with-moveable--change-the-moveable-targets-by-selecting-it

**Comment by DavidTschan** [comment]
Amazing, thanks for your help!
