### ISSUE TITLE
select box is at wrong position

### ISSUE THREAD

**Issue by winjeysong** [daybrush/selecto#100]
## Environments
* Framework name: react
* Framework version: 17.0.2
* Component name:  react-selecto@1.19.0 react-moveable@0.38.4
* Testable Address(optional): https://codesandbox.io/s/eloquent-violet-1dmfo9?file=/src/App.tsx

## Description

I set "transform: scale(0.5)" on container element, and set "rootContainer" prop, but select box is still at wrong position.

![image](https://user-images.githubusercontent.com/22495161/187867411-a6abbfd8-578e-452e-bca7-7e4b9b3e037e.png)

**Comment by daybrush** [comment]
@winjeysong 

selecto's new version is released. Check it again.

**Comment by winjeysong** [comment]
> @winjeysong
> 
> selecto's new version is released. Check it again.

thanks for your rapid response, but I still get something wrong...
It seems that `e.data` is undefined. 

![image](https://user-images.githubusercontent.com/22495161/188299417-ca39bbca-a65d-476e-ad7c-9022185444f4.png)
![image](https://user-images.githubusercontent.com/22495161/188299490-8a7c9953-4d02-4c97-990e-143feb2cb356.png)

**Comment by daybrush** [comment]
@winjeysong 

In my opinion, delete selecto and install it again. The version of gesto must be 1.13.0 or higher installed.

**Comment by winjeysong** [comment]
> @winjeysong
> 
> In my opinion, delete selecto and install it again. The version of gesto must be 1.13.0 or higher installed.

ok, thank you
