### ISSUE TITLE
select event don`t fire

### ISSUE THREAD

**Issue by SkyHolder** [daybrush/selecto#103]
## Environments
* Framework name: Vue
* Framework version: 2
* Component name: VueSelecto
* Component version: "^1.20.0"
* Testable Address(optional): https://daybrush.com/selecto/storybook/?path=/docs/selecto--select-in-real-time

## Description
Looks like event `select` not work, even at demo page in documentstion
it fire once when start selecting start inside selectable element (start select from middle of .cube for example)

now it is not possible to get a list of selected elements in the selection process =(

**Comment by daybrush** [comment]
@SkyHolder 

1.20.1 is released. Check it again.

**Comment by SkyHolder** [comment]
Perfect., thank you very much
