### ISSUE TITLE
Issue with destroy - Cannot read properties of null (reading 'unset')

### ISSUE THREAD

**Issue by adela-almasan** [daybrush/selecto#104]
## Environments
* Framework name: React
* Framework version: 17.0.2
* Component name: Selecto (+Moveable)
* Component version: 1.19.1

## Description

Hi! I'm having an issue when trying to destroy Selecto - as part of allowing/not allowing interactions. 
This is how I'm using it - `Selecto` is defined in all cases, so not sure about `gesto`.
```
if (inlineEditingSwitched && this.props.options.inlineEditing) {
    this.scene.selecto?.destroy();
}
```

![Screen Shot 2022-09-14 at 4 12 47 PM](https://user-images.githubusercontent.com/88068998/190263662-a55b73c6-aed6-42cd-805f-f36433e56775.png)

![Screen Shot 2022-09-14 at 4 13 11 PM](https://user-images.githubusercontent.com/88068998/190263618-0c6ef67b-7f98-408b-8187-f689232b80cf.png)

I'm still investigating on our end, but was wondering if you might have any ideas.

**Comment by daybrush** [comment]
@adela-almasan 

I think destroy is called destroy 2 times.
after calling destroy
 try setting `this.scene.selecto = null;`
