### ISSUE TITLE
How can I select elements even if the selection area has not covered them entirely?

### ISSUE THREAD

**Issue by jerwinaton** [daybrush/selecto#106]
![image](https://user-images.githubusercontent.com/53373461/199212836-1d3be1f6-d300-4d8e-b7d5-db5d9a42c711.png)
How can I select elements even if the selection area has not covered them entirely, just like in the image? 

The 'selected' class is only applied when the selection area has covered the elements entirely.

**Comment by xzhuah** [comment]
This is a great question, no idea why it is cloed without any explanation

**Comment by xzhuah** [comment]
The answer is to set hitRate. When hitRate is 100, the element will be only selected if 100% of it is within the drag area. 

If you set it to 1, then it means when 1% of it is covered, it will be selected
