### ISSUE TITLE
Vue code for Select in scroll aread needs to be updated.

### ISSUE THREAD

**Issue by sachinbro** [daybrush/selecto#111]
## Environments
* Framework name: Vue
* Framework version:
* Component name: vue3-selecto
* Component version:^1.6.2
* Testable Address(optional): 

## Description
Demo code for Vue in [here](https://daybrush.com/selecto/storybook/?path=/story/selecto--select-in-the-scroll-area), line no 206 is incomplete. 
in line 206:` this.$refs.selecto.` is it's missing `.checkScroll()`
should be `this.$refs.selecto.checkScroll()` as mentioned in [this issue]( https://github.com/daybrush/selecto/issues/107) by @jerwinaton 

Please update it ASAP. Thanks

**Comment by daybrush** [comment]
@sachinbro 

Fixed typos in vue code. Let me know if there are any other parts.

Thank you :)
