### ISSUE TITLE
onSelectEnd event - onClick - is false when element is clicked

### ISSUE THREAD

**Issue by frankvdb7** [daybrush/selecto#112]
## Environments
* Framework name: Angular
* Framework version: 14
* Component name: Selecto
* Component version: 1.20.2
* Testable Address(optional):  https://codesandbox.io/s/blue-lake-jo70qx

## Description
We are currently experiencing a bug with the Selecto component that the onSelectEnd event onClick property is false when clicking a selectable element, while it should be true. Clicking just outside the element sets the isClick property to true.

We'd expect the onSelectEnd event isClick property to be true in any case where there is a click (so if the mouse down and up is released within a certain time frame).

Please check the example for reference.

Thanks

**Comment by daybrush** [comment]
@frankvdb7 

click is an event that fires when mouseup occurs.

Try using e.isDragStart instead of e.isClick for selectEnd that occurred on mousedown.
