### ISSUE TITLE
Vertical line always selected even if not within selection

### ISSUE THREAD

**Issue by m-damien** [daybrush/selecto#117]
## Environments
* Framework name: React
* Framework version: 18.2.0
* Component name: Selecto
* Component version: 1.20.3
* Testable Address(optional): https://codesandbox.io/s/crazy-franklin-o5fe10

## Description
Thank you for this library, it has been a pleasure to work with it so far!
I am having an issue with vertical SVG lines. They seem to be getting selected even when they are not part of the selection:
![line_selection](https://user-images.githubusercontent.com/45567853/211221566-e3214d8d-2df1-4cf8-b933-1ba154dadf6d.gif)
I was able to reproduce the issue starting from one of the examples from the Storybook (see the testable address above). Seems to be fine with horizontal line, or lines that are not perfectly vertical.

**Comment by daybrush** [comment]
@m-damien 

* `lit-selecto` 1.21.0
* `preact-selecto` 1.18.0
* `react-selecto` 1.21.0
* `selecto` 1.21.0
* `svelte-selecto` 1.21.0
* `vue-selecto` 1.21.0
* `vue3-selecto` 1.7.0
* `ngx-selecto` 1.21.0


selecto's new version is released.

Check it again.

**Comment by m-damien** [comment]
That was impressively quick! I tried the new version, the problem is completely fixed.

Thanks heaps!
