### ISSUE TITLE
Hide control box for specific targets

### ISSUE THREAD

**Issue by adela-almasan** [daybrush/selecto#118]
## Environments
* Framework name: React
* Framework version: 17.0.2
* Component name: Selecto (1.22.0) + Moveable (0.43.1)

## Description
Hey @daybrush! I'm trying to find a way to hide the moveable control box for certain elements (and apply my own styling), while still keeping the ability to select them. I'm not sure if this can be achieved with the current implementation and would appreciate your input. 

I think a suggestion would be to have `selectableTargets` as an array of objects with a property for that and hide/display according to that property. That would possibly allow even more custom functionality. 

Thank you!

**Comment by daybrush** [comment]
@adela-almasan 

How about setting selectableTargets to filter?

```tsx
selectableTargets={selectableTargets.filter(target => target.display)}
```

**Comment by adela-almasan** [comment]
Closing this one in favor of https://github.com/daybrush/moveable/issues/848. Ty!
