### ISSUE TITLE
where is documentation ?

### ISSUE THREAD

**Issue by djmisterjon** [daybrush/selecto#122]
hi, where is documentation ?
Do i have wrong type définition?
How know what field do without jsdoc ? 
![image](https://user-images.githubusercontent.com/24865815/227721112-48579e2f-6ebf-4942-9e33-5a470beec399.png)

**Comment by daybrush** [comment]
@djmisterjon 
https://daybrush.com/selecto/release/latest/doc/Selecto.html#.SelectoOptions

I will expose jsdoc to d.ts of selecto.

**Comment by djmisterjon** [comment]
thank friend
