### ISSUE TITLE
keydown event does not appear to be working.

### ISSUE THREAD

**Issue by sunecosuri** [daybrush/selecto#123]
## Environments
* Framework name: Vue.js
* Framework version: 2.6.12
* Component name: vue-selecto
* Component version: 1.22.1
* Testable Address(optional): 

## Description

Hi, I'm finding it very useful, but I have one question.
the keydown event doesn't seem to be working, am I using it wrong...?

Change the code as follows and run `yarn serve` to access on http://localhost:8080 after git  repo clone.
https://github.com/daybrush/selecto/blob/master/packages/vue-selecto/demo/App.vue#L93-L95

```diff
--    onKeydown() {
++    onKeydown(event) {
++    console.log(event)
      document.querySelector(".button").classList.add("selected");
    },
```

## Reproduction steps

```
cd ./packages/vue-selecto
yarn install
// Change the code as above
yarn dev
// access to http://localhost:8080
```

**Comment by daybrush** [comment]
@sunecosuri 

It doesn't seem to be set to app.vue.

When I do it with app.vue, it works fine.



```tsx
import Vue from 'vue';
import App from './App.vue';
// import App from './InfiniteViewer.vue';


new Vue({
  render: (h: any) => h(App),
}).$mount('#app');

```

**Comment by sunecosuri** [comment]
You made a mistake in your verification process. It worked out fine. Thanks!

**Comment by sunecosuri** [comment]
@daybrush 
Please close this issue. Thank you very much.
