### ISSUE TITLE
How can I make table rows selectable?

### ISSUE THREAD

**Issue by yesvivek** [daybrush/selecto#13]
## Environments
* Framework name: Javascript

## Description
I need table rows to be selected and trying to achieve that using selecto. Attached a sample code that I have been trying and my intention is I should be able to select the rows by clicking them individually (which works) and also by dragging mouse over TRs, which I dont know how to achieve. Can someone help me to achieve it?

[selectable.html.txt](https://github.com/daybrush/selecto/files/5104715/selectable.html.txt)

**Comment by daybrush** [comment]
@yesvivek 
If what I'm thinking is correct, would you set the hitRate option to 0?
