### ISSUE TITLE
Can not select node on click (only with dragging blue box)

### ISSUE THREAD

**Issue by zsoerenm** [daybrush/selecto#130]
## Environments
* Framework name: Lit
* Framework version: 3.3.1
* Component name: selecto
* Component version: 1.22.2
* Testable Address: https://stackblitz.com/edit/lit-element-typescript-demo-vpuvyn?file=moveable-elements.ts

## Description
I'm not able to select a single node on click event. Nodes can only be selected when dragging the blue box.

https://user-images.githubusercontent.com/375486/234387641-b7563202-3a0c-4df1-968a-55933750aacf.mp4

In the video I try to select the element by clicking, but it doesn't get selected.

See testable address.

**Comment by daybrush** [comment]
@zsoerenm 

Try updating moveable to the new version.

**Comment by zsoerenm** [comment]
Thanks for looking into this!
I updated moveable to version 0.47.0, but I'm still not able to select a single target by clicking on it:
https://stackblitz.com/edit/lit-element-typescript-demo-xpmydt?file=package.json

**Comment by daybrush** [comment]
@zsoerenm 

selecto's new version is released. (selecto@1.22.3)

Try it again.

**Comment by zsoerenm** [comment]
Yes, this does work now. Thank you very much!
