### ISSUE TITLE
Conditional Hit rate

### ISSUE THREAD

**Issue by hoondeveloper** [daybrush/selecto#138]
## Environments
* Framework name: React
* Framework version: ^18
* Component name: react-selecto
* Component version: 1.22.6
* Testable Address(optional): 

## Description

There is a requirement to give different props for each node, such as Hit Rate 0 for some nodes and Hit Rate 100. What can we try to implement these features?

**Comment by hoondeveloper** [comment]
https://github.com/daybrush/selecto/pull/139

**Comment by daybrush** [comment]
@hoondeveloper 

* `lit-selecto` 1.23.0
* `preact-selecto` 1.20.0
* `react-selecto` 1.23.0
* `selecto` 1.23.0
* `svelte-selecto` 1.23.0
* `vue-selecto` 1.23.0
* `vue3-selecto` 1.9.0
* `ngx-selecto` 1.23.0

selecto's new version is released. Thank you :)
