### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by hoondeveloper** [daybrush/selecto#140]
## Environments
* Framework name: react
* Framework version: ^18
* Component name: react-selecto
* Component version: latest
* Testable Address(optional): 

## Description

if there are many elements that is selectable, selecto/moveable performance goes slow down.

(we could know some insights that `flushSync` makes performance slow down in below screenshot)

<img width="1511" alt="스크린샷 2023-06-26 오후 11 50 38" src="https://github.com/daybrush/selecto/assets/32122626/78213cf9-093a-4344-adce-23d14ecc53f5">

**Comment by daybrush** [comment]
@hoondeveloper 

Since selecto and Moveable are both DOM, we know that if there is a lot of DOM around it, it will be slow.

Are there any examples I can test on?

**Comment by hoondeveloper** [comment]
I investigated this issue further, and it turns out to be a performance issue with my app, which I apologize for.
