### ISSUE TITLE
Clicking a single item to deselect items makes the clicked item follow the cursor until clicked again (sticky element)

### ISSUE THREAD

**Issue by davidalejandroaguilar** [daybrush/selecto#141]
## Environments
* Framework name: StimulusJS
* Framework version: 3.2.1
* Moveable Component version: 0.49.1
* Testable Address(optional): https://codepen.io/davidalejandroaguilar/pen/gOQmwQB

## Description

When clicking a single item of selected items, the element sticks to the cursor and follows the mouse around until you click again.

The expected behavior is that the single click on one of the selected items, selects one item and the item doesn't automatically follow the cursor.

This happens in every example in the Moveable and Selecto storybooks too. [Example here](https://daybrush.com/moveable/storybook/?path=/story/combination-with-other-components--components-selecto).

https://github.com/daybrush/selecto/assets/15317732/112d868a-f088-406a-b896-b87c91c099a6

If you change `selectFromInside` to `true`, the issue is fixed, but now you can't click and drag a single item, you have to click and drag to select:

https://github.com/daybrush/selecto/assets/15317732/82c313d2-7e61-4632-b16d-7d3c29afc8b1

**Comment by daybrush** [comment]
@davidalejandroaguilar 

selecto's new version is released. Cehck it again

**Comment by davidalejandroaguilar** [comment]
Thank you very much!
