### ISSUE TITLE
support classname prop

### ISSUE THREAD

**Issue by hoondeveloper** [daybrush/selecto#142]
## Environments
* Framework name: react
* Framework version: ^18
* Component name: react-selecto
* Component version: latest
* Testable Address(optional): 

## Description

i have needs to pass classname to selecto, but there is no way to pass it. could you support `className` prop

**Comment by daybrush** [comment]
@hoondeveloper 

released as a new version. try to update. and use `className` prop

**Comment by hoondeveloper** [comment]
Thank you so much!!!
