### ISSUE TITLE
content-visibility freeze selecto performance issue 

### ISSUE THREAD

**Issue by djmisterjon** [daybrush/selecto#148]
## Environments
* Framework name: vanilla dom

## Description
Actually if we use `content-visibility: auto` 
Selecto get freezed ~1 seconde before start !
![image](https://github.com/daybrush/selecto/assets/24865815/8ec0b63a-e97b-4042-b00f-b3dab0ffbdf6)

if i remove `content-visibility: auto` , the issue or overflow , it remove the issue.

Did you have option or a fix for special case with `content-visibility: auto`  ? 
This is used to give a 50% perf boost in my app but selector seem dont like .

**Comment by daybrush** [comment]
@djmisterjon 

<img width="1256" alt="image" src="https://github.com/daybrush/selecto/assets/3433062/006420eb-2625-4491-85da-3a4f53d8da3a">



I've tested content-visibility, but I can't figure it out.

Could you also show the area of mousedown in detail via performance tab?

Also, will there be a test address?

**Comment by djmisterjon** [comment]
@daybrush 

fixed by remove children rules !
Not sure why but with those childs css rules for contaiment will make selecto drop to ~15fps 😐!

![image](https://github.com/daybrush/selecto/assets/24865815/07133a8f-62a3-42b8-a93d-c935f821b29a)
---
![image](https://github.com/daybrush/selecto/assets/24865815/4cc90592-f72f-4626-82df-feb25cb4fe0a)
---
![image](https://github.com/daybrush/selecto/assets/24865815/051efb68-e5c1-4e00-bfc3-2c757ac7c2ef)
