### ISSUE TITLE
selectByClick:false  is not working 

### ISSUE THREAD

**Issue by pomelovico** [daybrush/selecto#15]
## Environments
* Framework name: React
* Framework version: v16
* Component name: 
* Component version:
* Testable Address(optional): 

## Description
When I set `selectByClick` to false,  the item still could be selected by single click, but when I set `selectFromInside` to false, it works，but another problem occurs: I can not selected item from inside...It makes me confused, as you can see in your demo...

**Comment by daybrush** [comment]
@pomelovico 

selecto new version is released.
this bug and demo are fixed.

check it again
