### ISSUE TITLE
toggleContinueSelect is not effective in particular case

### ISSUE THREAD

**Issue by yesvivek** [daybrush/selecto#16]
* Framework name: Vanilla JS
* Testable Address(optional): https://codepen.io/yesvivek/pen/LYNbQdo

I have been trying to use selecto to select rows in the table. I want to allow selection of rows using keyboard and also using mouse. I take care of keyboard selection and selecto is used only for mouse selection. Whenever keyboard is used, I use _selecto.setSelectedTargets_ to set the current selection and it works fine so far.

This particular problem arises only when mixing keyboard and mouse. Follow below steps on above sample page that is created to reproduce this issue. I have used textbox instead of up or down arrow key because I started with textbox first. I can rewrite to use keyboard event if needed or simplify reproduction sample.

1. Click on row 6 (any row other than 2).
2. Press Shift key.
3. Click Add button which will select row 2.
4. Do not release Shift key.
5. Press some key (Down arrow)
6. Do not release shift key.
7. Click on new row.
8. Now old selection is removed 

Callbacks are called with _removed_ containing previously selected elements even though Shift (toggle) key is still pressed.
Am not sure whether this is a bug or I need to set _keyContainer_ option with different value. Please advice.

**Comment by yesvivek** [comment]
Actually now I can see the same issue even if I skip step 3 and 4. Updated steps,

1. Click on any row.
2. Press Shift key.
3. Press some key (Down arrow)
4. Do not release shift key.
5. Click on new row.
6. Now old selection is removed

**Comment by yesvivek** [comment]
@daybrush , should I handle keydown and keyup event triggered by Selecto to do something about this? Appreciate your help..

**Comment by daybrush** [comment]
@yesvivek 

thank you. it's bug.I will fix it and let you know again tomorrow.

**Comment by yesvivek** [comment]
@daybrush thank you for the confirmation.

**Comment by daybrush** [comment]
@yesvivek 

selecto's new version is released. Check it again.

**Comment by yesvivek** [comment]
Works perfectly now @daybrush , thank you for fixing this.
