### ISSUE TITLE
Selection continues even after switching tabs

### ISSUE THREAD

**Issue by yesvivek** [daybrush/selecto#19]
* Framework name: Vanilla JS
* Testable Address(optional): https://codepen.io/yesvivek/pen/LYNbQdo
* OS: Windows
* Browser: Chrome

Am using Selecto to select table rows and has been working good. One problem I notice when using Ctrl and/or shift `toggleContinueSelect` is that when moving away from the page using Ctrl+Tab and returning back makes Selecto think that I keep pressing Ctrl/shift and it continues to select without removing old selection.

Reproduction steps to follow on above page (or in your demo page):

1. Select any row in the table.
2. Use Ctrl+tab to navigate to next tab in the window.
3. Do whatever you wanted to do on the next tab.
4. Switch back to the selecto page.
5. Select any row.
6. Previous selection is not cleared.

Notice that I never intended to use Ctrl for selection at all.

**Comment by yesvivek** [comment]
@daybrush do you see this issue?

**Comment by daybrush** [comment]
@yesvivek 

Thank you. I'll fix it

**Comment by daybrush** [comment]
@yesvivek 

* selecto 1.7.1
* react-selecto 1.7.1
* preact-selecto 1.6.1
* ngx-selecto 1.7.1
* lit-selecto 1.7.1
* vue-selecto 1.7.1
* svelte-selecto 1.7.1



selecto new version is released. Check it again

**Comment by yesvivek** [comment]
@daybrush , https://daybrush.com/selecto/release/latest/dist/selecto.min.js is at 1.7.2, but I still see the issue, please check here, https://codepen.io/yesvivek/pen/LYNbQdo.

**Comment by daybrush** [comment]
@yesvivek 

selecto 1.7.3 is released.

now it's working. Check it again.

**Comment by yesvivek** [comment]
Thank you @daybrush !! That fixed the issue..
