### ISSUE TITLE
Editable on double click.

### ISSUE THREAD

**Issue by saurabhsksharma** [daybrush/selecto#2]
## Environments
* Framework name: Angular
* Framework version: 9.1.0
* Component name: Selecto + Moveable
* Component version: latest
* Testable Address(optional): 

## Description

I created a moveable component that having text. Using selecto, it can be selected on a single click. I need it to be editable on a double click. Is it possible through your library?

**Comment by daybrush** [comment]
@saurabhsksharma 
dbl click is not supported.

but it can be check `contenteditable`

selecto.on("dragStart", e => {
   if (e.inputEvent.target.getAttribute("contenteditable")) {
        e.stop();
   }
});

**Comment by prasanthLalapeta** [comment]
@daybrush Guess we can set `target={null}` to **Moveable** on double click of same element.
