### ISSUE TITLE
Selection drag area positioned incorrectly for container positioned with transform

### ISSUE THREAD

**Issue by geoffbullen** [daybrush/selecto#23]
## Environments
ngx-selecto

## Description
Hi, when I position the selecto container in the middle of a page using a transform.   The drag selection drag box is positioned in the wrong place.   

I centered the container like this.  If I remove the transform, it all works fine.

`.container {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    margin: 0;
}
`

![image](https://user-images.githubusercontent.com/2024640/95940247-9ddebb80-0e29-11eb-8276-a7bd782a1260.png)

If this isn't easy to fix, is it possible to hide the drag area during the selection process?

**Comment by daybrush** [comment]
@geoffbullen 

Is there a selecto in the container?
Even if the position is fixed, if the parent element has a transform, it is transformed.
I don't think it should be placed in a container.
Sorry.

**Comment by geoffbullen** [comment]
Hi @daybrush,  

Here is an example based on your demo https://codesandbox.io/s/wizardly-banzai-3mmgm 

Thanks a lot for the project by the way!  Very cool

If its not possible, could you point me at the correct css class to hide the selection visualisation during the drag?

**Comment by daybrush** [comment]
@geoffbullen 

```html
<div class="app">
    <ngx-selecto
    dragContainer=".elements"
    [selectableTargets]='[".selecto-area .cube"]'
    [hitRate]="100"
    [selectByClick]="true"
    [selectFromInside]="true"
    [ratio]="0"
    (selectStart)="onSelectStart($event)"
    (selectEnd)="onSelectEnd($event)"
  ></ngx-selecto>
  <div class="container">
    <div class="elements selecto-area" id="selecto1">
      <div class="cube" *ngFor="let num of cubes"></div>
    </div>
    <div class="empty elements"></div>
  </div>
</div>
```


Or if you don't want to show css:
```css
.selecto-selection {
opacity: 0;
}
```

**Comment by geoffbullen** [comment]
Ah, thanks so much @daybrush... you've made my day

**Comment by tom2strobl** [comment]
Sorry for posting into a closed issue, but I just ran into the same issue (setting a rootContainer did not help) and saw that `.selecto-selection` always has `top: 0; left: 0` set in the inline style tag, so
```css
.selecto-selection {
    top: -${topOffset}px !important;
    left: -${leftOffset}px !important;
}
```
simply _"countered"_ the offset that my container had. The positioning itself happens in a `transform` anyway.
`!important` sucks, but it seems to do the job in this case. In `SelectoManager.tsx` on Line 723 where the inline css is set I can see that left and top are statically set to 0, so I'm hoping there are no calculation conflicts.
