### ISSUE TITLE
Selecting only when clicking on the container

### ISSUE THREAD

**Issue by brunobg** [daybrush/selecto#24]
## Environments
* Framework name: pure JS

## Description
Is it possible to only start selection only when clicking on the actual background container, not on the objects themselves? I'm using selecto (without moveable) and when I click to drag an element selecto also starts selecting. I tried `selectFromInside: false`, but there was no effect.

**Comment by daybrush** [comment]
@brunobg 
* selecto 1.7.1
* react-selecto 1.7.1
* preact-selecto 1.6.1
* ngx-selecto 1.7.1
* lit-selecto 1.7.1
* vue-selecto 1.7.1
* svelte-selecto 1.7.1
selecto new version is released. Check it again

**Comment by brunobg** [comment]
Thanks a lot!
