### ISSUE TITLE
svelte-selecto package broken?

### ISSUE THREAD

**Issue by fsmoreir** [daybrush/selecto#28]
## Environments
* Framework name: selecto
* Framework version: 1.10.1
* Component name: svelte-selecto
* Component version:1.10.1
* Testable Address(optional):  https://codesandbox.io/s/6u5gu

## Description

In all examples (in code sandbox)  an error is thrown when you click in a selectable area. this occurs only  for svelte-selecto (and lit). For the other packages. Tested on Chrome and Firefox (latest stable - win 10).

**Comment by daybrush** [comment]
@fsmoreir 

Oh, Thank you.  svelte-selecto 1.10.2 is released. Check it.

**Comment by fsmoreir** [comment]
Now it is working. I´ve tested it on codesandbox. Although there, the latest svelte-selecto is not yet 1.10.2. If we change in package,json
  "dependencies": 
    "svelte-selecto": "1.10.2"
Everything is working as expectd.
Thank you very much for your work.
