### ISSUE TITLE
in the dragContainer have a textarea and can not click and  type, because selecto prevented this behavior， how to exclude some element in drag area?

### ISSUE THREAD

**Issue by leeboo** [daybrush/selecto#3]
in the dragContainer have a textarea and can not click and  type, because selecto prevented this behavior， how to exclude some element in drag area?
![image](https://user-images.githubusercontent.com/1256745/84116851-3079e300-aa63-11ea-9adf-dc6af256f8de.png)

**Comment by daybrush** [comment]
@leeboo 

`selecto` has dragStart event.

```js

selecto.on("dragStart", e => {
    if (e.inputEvent.target.tagname === "TEXTAREA") {
        e.stop();
    }
});

**Comment by Jomimoses** [comment]
I too faces the similar issue.
i have enabled the selectByClick={true} to select the element but prevents the textArea edit 
in this code the contentEditable not working
 <Selecto
![screenshot-localhost_3000-2020 06 10-08_09_15](https://user-images.githubusercontent.com/37336949/84220963-b8a6c980-aaf1-11ea-8cb4-0e29007e42c2.png)

        ref={selectoRef}
        dragContainer={"#pdf"}
        selectableTargets={[".dg"]}
        hitRate={0}
        selectByClick={false}
        selectFromInside={false}
        toggleContinueSelect={["shift"]}
        onDragStart={e => {
          const moveable = moveableRef.current;
          const target = e.inputEvent.target;
          if (
            moveable.isMoveableElement(target) ||
            (targets && targets.some(t => t === target || t.contains(target)))
          ) {
            e.stop();
          }
        }}
        onSelectEnd={e => {
          const moveable = moveableRef.current;
          setTargets(e.selected);
          setEditable(false);
          if (e.isDragStart) {
            e.inputEvent.preventDefault();
            setTimeout(() => {
              moveable.dragStart(e.inputEvent);
            });
          }
        }}
      ></Selecto>
      <div ref={drop} id="pdf" className="a4">
        <div className="row">
          <div className="col">
            {elements.map((data, i) => (
              <div key={i} contentEditable="true">
                {data}
              </div>
            ))}
          </div>
        </div>
      </div>

**Comment by daybrush** [comment]
@Jomimoses 

The elements that can input text (input, textarea, contentEditable) are not dragged.
You have to check all of this at the start of dragStart.

**Comment by leeboo** [comment]
thanks
