### ISSUE TITLE
[Feature] Fixed height for selection box

### ISSUE THREAD

**Issue by benwoodward** [daybrush/selecto#32]
`boundContainer` is really useful, what I'd like is prop that builds on this functionality by allowing me to specify a fixed height. Meaning that dragging a selection only allows you to modify the width of a selection but not the height. What I'm using this for is to make it possible to create selections on a timeline, so I'm trying to recreate selection behaviour you might find in Final Cut or Premiere.

**Comment by daybrush** [comment]
@benwoodward 

The boundContainer type was added.

```js
boundContainer: {
   element: HTMLElement,
   left: true,
   top: true,
   bottom: true,
   right: true,
},
```

**Comment by benwoodward** [comment]
Thank you!
