### ISSUE TITLE
[Bug] svelte-selecto logs to console on initialisation

### ISSUE THREAD

**Issue by benwoodward** [daybrush/selecto#34]
## Environments
* Framework name: svelte-selecto
* Framework version: 1.10.2
* Component name: Selecto.svelte
* Component version: ??

## Description
There is a `console.log` statement in the `svelte-selecto` package, its not possible for me to disable this in production because it's not wrapped in a conditional. Ideally developer logs shouldn't be visible in production.

https://github.com/daybrush/selecto/blob/fd58600ee1178484f401367a05c017e517a999e9/packages/svelte-selecto/src/svelte-selecto/Selecto.svelte#L54

**Comment by daybrush** [comment]
@benwoodward 

Oh, sorry. I'' fix it.

**Comment by benwoodward** [comment]
No worries! Thanks for sharing this code 👍🏻

**Comment by daybrush** [comment]
@benwoodward 


1.10.3 is released. It's fixed. Thank you :)
