### ISSUE TITLE
Selection drag area shifted when container parent has transform 

### ISSUE THREAD

**Issue by vasylHordynskyy** [daybrush/selecto#35]
## Environments
* Framework name: React
* Framework version: 1.17
* Component name: react-selecto
* Component version: 1.10.2
* Testable Address(optional): https://codesandbox.io/s/compassionate-beaver-0cpbo?from-embed=&file=/src/App.tsx:476-487

## Description
Hi, when selecto container is placed in parent which already is transformed then selection drag area is positioned incorrectly. I have attached modified example to reproduce this behaviour.
Of cource as workaround I can hide drag area but I would like to have it in right place.  

Thanks in advance.

**Comment by daybrush** [comment]
@vasylHordynskyy 
I'm sorry. If there is selecto in the transformed container, operation is not possible. Since selecto is position: fixed, the behavior becomes weird if there is a transform.
