### ISSUE TITLE
how to select all elements by pressing a specific button?

### ISSUE THREAD

**Issue by devoicy** [daybrush/selecto#37]
## Environments
* Framework name:
* Framework version:
* Component name: 
* Component version:
* Testable Address(optional):

**Comment by daybrush** [comment]
@devoicy 

* `selecto` 1.11.0
* `react-selecto` 1.11.0
* `preact-selecto` 1.10.0
* `ngx-selecto` 1.11.0
* `svelte-selecto` 1.11.0
* `lit-selecto` 1.11.0
selecto's new version is released.

Use getSelectableElements method
```js
const elements = selecto.getSelectableElements();

selecto.setSelectedTargets(elements);
```

**Comment by devoicy** [comment]
why is the target outside the container also selected?

**Comment by daybrush** [comment]
@devoicy 

Isn't container included in selectableTargets?

Are there any demos I can test?

**Comment by devoicy** [comment]
Demo https://codepen.io/devoicy/pen/xxgGErW

it's my fault for not understan it, the target must be precise. selectableTargets: ["#main .list-group-item"]
