### ISSUE TITLE
Blur/Focus issue with selecto

### ISSUE THREAD

**Issue by happylinks** [daybrush/selecto#4]
## Environments
* Framework name: React
* Framework version: 16.8.0
* Component name: Selecto
* Component version: 1.1.1
* Testable Address(optional): 
https://codesandbox.io/s/cool-roentgen-6u4ib

## Description

Text inputs do not get a onBlur event anymore, and focus does not move away.

Please see this demo: https://codesandbox.io/s/cool-roentgen-6u4ib
1. Click in the text input
2. Start a selection
3. Blur is not triggered & focus stays on the input

I have an editor with textfields around a canvas, when a user changes a text in the textfield and then starts a selection, the blur is not triggered, meaning I don't know that I should save the textlayer.
Also, the focus stays on menus that should not have focus after clicking on the canvas.

**Comment by daybrush** [comment]
@happylinks 

Because it preventDefault when dragstart, focus is not out from input. Add the following code.
```js
<Selecto
          onDragStart={e => {
            if (document.activeElement.tagName === "INPUT") {
              (document.activeElement as HTMLInputElement).blur();
            }
          }}

/>
```

**Comment by happylinks** [comment]
Great answer, worked perfectly!

I put it on contenteditable and BUTTON as well :)

Thanks!
