### ISSUE TITLE
Has one way to use window.scroll as a scroll Option ?

### ISSUE THREAD

**Issue by dnb00** [daybrush/selecto#40]
Hello, there's anyway to use window scroll as an option ? Without using a container to get her ref.
I've tried to follow the docs but i didn't succeed using `window.scroll`

**Comment by daybrush** [comment]
* `selecto` 1.11.1
* `react-selecto` 1.11.1
* `preact-selecto` 1.11.1
* `ngx-selecto` 1.11.1
* `svelte-selecto` 1.11.1
* `lit-selecto` 1.11.1

@dnb00 

selecto's new version is released.

use document.body instead of window

**Comment by dnb00** [comment]
Don't work. @scroll is never called 

I'm using `vue-selecto ` 1.11.1 

I think I'm doing something wrong

**Comment by daybrush** [comment]
@dnb00 


Set threshold 30 (> 0)

If the threshold is 0, it is the level at which the mouse moves out of the browser.

**Comment by dnb00** [comment]
@daybrush ok, now when i scroll the box down, the scroll moves too, but my inputs are not selected
Is there anything else i have to do?

https://files.slack.com/files-pri/T02CV8PKB-F01TPN1JT09/img_20210405_160313.png

**Comment by dnb00** [comment]
Oh sorry, i didn't see your anwser

So, when i'm scrolling down the selector box goes down too, but without selecting my items

[New Image Uploaded](https://ibb.co/XW82xys)

**Comment by daybrush** [comment]
@dnb00 

Is there any address I can test?

**Comment by dnb00** [comment]
I think is not necessary anymore, thank you for your time
