### ISSUE TITLE
When the parent container contains "transform:'scale(1)'", the selection box position is incorrect.

### ISSUE THREAD

**Issue by xjb258** [daybrush/selecto#44]
## Environments
* Framework name:
* Framework version:
* Component name: 
* Component version: 1.11.1
* Testable Address(optional): 

## Description
When the parent container contains css style: "transform:'scale(1)'", the selection box position is incorrect.
The reason for the error: the start and end positions of the selected rectangle have not been converted.

**Comment by xjb258** [comment]
![无标题](https://user-images.githubusercontent.com/12584516/116938938-114cfb00-ac9e-11eb-8960-26b3d759817b.png)

**Comment by xjb258** [comment]
![9ns6w-u7lvu](https://user-images.githubusercontent.com/12584516/116980141-733a4e80-acf8-11eb-82bb-14a9f2e60957.gif)

**Comment by xjb258** [comment]
@daybrush @gillisig @sibbng

**Comment by xjb258** [comment]
resoved

**Comment by georgezouq** [comment]
@xjb258 how to resolve this problem?

**Comment by satheshrgs** [comment]
@daybrush How to resolve this ? Facing this issue

**Comment by daybrush** [comment]
@satheshrgs @georgezouq 

If there is a transform in the container, please refer to the following
https://github.com/daybrush/selecto/issues/49

**Comment by satheshrgs** [comment]
@daybrush the transform: scale is at the parent level
