### ISSUE TITLE
How can I change the style of drag area?

### ISSUE THREAD

**Issue by YahngSungho** [daybrush/selecto#46]
Thank you for building such a nice library.

I have one question. I want to style the area created from the mouse cursor when dragging.

![dragArea](https://user-images.githubusercontent.com/29212791/119565578-173d8400-bde5-11eb-90ff-8a5a67e600f9.png)

But I have no idea what the class of this is. Even when I look through the code of this library, I couldn't find the part that sets its style. How do I modify CSS to change its style?

**Comment by r0nsha** [comment]
The class of the drag area is selecto-selection :)
![image](https://user-images.githubusercontent.com/44722426/120036864-6f54d000-c009-11eb-99c2-eb8ad4e6d577.png)
