### ISSUE TITLE
How can i remove selected by clicking the outside area of Selecto?

### ISSUE THREAD

**Issue by Eiputoo** [daybrush/selecto#5]
## Environments
* Framework name: React Hooks
* Framework version:
* Component name: 
* Component version:
* Testable Address(optional): 

## Description

Hello again @daybrush , Thank you so mush for great plugin. I'm using react-moveable with selecto as [https://daybrush.com/selecto/storybook/?path=/story/selecto-with-moveable--select-moveable-targets-in-real-time].

In your example, selection is unselect by clicking within this `".selecto-area .elements"` div.
I would like to remove selection by clicking outside area of Selecto. 
I tried with two option,
First option with `setTargets([])` to remove selection and it was remove the selection but i can't select items again.
Second option is i add `".selecto-area .elements"` class to body tag. But other click event doesn't work inside that body.

Do you have any example like that please?

**Comment by daybrush** [comment]
@Eiputoo 

```js
setTargets([])
```
And Call setSelectedTargets
```js
selecto. setSelectedTargets([]);
```

**Comment by Eiputoo** [comment]
@daybrush ,

When i added ` selecto. setSelectedTargets([]); `, it's showing error like this **Cannot find name 'selecto'.**

**Comment by daybrush** [comment]
@Eiputoo 

In this code:
```js
selectoRef.current.setSelectedTargets([]);
```

**Comment by Eiputoo** [comment]
@daybrush , it's working, I really appreciate for your help!

**Comment by phantrongbien** [comment]
> @daybrush , it's working, I really appreciate for your help!
Hello @Eiputoo 
Can you share the code.

I get the text content of the selected object and push it to the input. And I want to click outside, it will delete the content of the input. 
But I still can't do it.

Please help me

**Comment by iBasit** [comment]
doesn't work as expected. This issue should be reopen.
