### ISSUE TITLE
Selecto to select desired target using code instead of mouse click

### ISSUE THREAD

**Issue by carlesknn9988** [daybrush/selecto#50]
May I know is this possible to use selecto to select desired target using code instead of mouse click on the target object?

I am trying to achieve something like click one single target object (target1) to also select other target object (target2) programmatically that are grouped.

For example:

```
<div class="moveable target" id="target1">target 1 under group 1</div>

<div class="moveable target" id="target2">target 2 under group 1</div>
```

```javascript
const selecto = new Selecto({
      container: document.body, 
      selectableTargets: [".target"],
      hitRate: 80,
      selectByClick: true, 
      selectFromInside: false,
      continueSelect: false,
      boundContainer: true,
      toggleContinueSelect: ["shift"],
      ratio: 0,
  });
```

**Comment by jessejamesrich** [comment]
I believe adding the class selected makes it selected. I haven't tested this, but I think _something_ like this would work.

```
functionToSelectAndMove = () => {
var targets = document.getElementsByClassName("target");
for(var i = 0;i< targets;i++) 
targets[i].classList.add("selected");
targets[i].style.left = '100px';
targets[I].style.top = '100px';
}
```

**Comment by carlesknn9988** [comment]
> I believe adding the class selected makes it selected. I haven't tested this, but I think _something_ like this would work.
> 
> ```
> functionToSelectAndMove = () => {
> var targets = document.getElementsByClassName("target");
> for(var i = 0;i< targets;i++) 
> targets[i].classList.add("selected");
> targets[i].style.left = '100px';
> targets[I].style.top = '100px';
> }
> ```

Thanks for the suggestion. This idea has inspired me to use another work around to set moveable target programmatically. And It is working for my use case now. Thanks
