### ISSUE TITLE
Abort Drag after OnDragStart

### ISSUE THREAD

**Issue by JonathanTreffler** [daybrush/selecto#60]
## Environments
* Framework name: Vue
* Framework version: 2

## Description
I want to abort a drag, if my program is in a specific mode and if it is not a selectByClick (= without mouse drag).
But the gesto object provided by the OnDragStart Event does not know yet if it is a drag, so the isDrag property is still false, even if the user goes on to drag the mouse.

There are 2 potential solutions, but I have not been able implement any of them:
- There is a way to abort the drag from inside a onDrag Event
- There is a way to disable drag selecting temporarily, without disabling the selectByClick functionality

Yes I could add another click event listener to the object directly, reimplement the selectByClick functionality and completely disable select during the before-mentioned program mode, but that would mess up my data flow:
Selecto events set the selected objects in my program state store and add the selected elements to the moveable targets.
It would be very messy to have two event types that cause changes to the moveable targets (from 2 components)

**Comment by daybrush** [comment]
@JonathanTreffler 


I'm going to make a function that can stop while dragging.

If it is stopped during dragging, all subsequent events (drag, dragEnd, select, selectEnd) do not occur.

**Comment by JonathanTreffler** [comment]
Great :)

**Comment by daybrush** [comment]
@JonathanTreffler 

vue-selecto@1.13.2 is released.

Try it again


```js
onDrag(e) {
    e.stop();
}
```

**Comment by daybrush** [comment]
@JonathanTreffler 

I'm sorry. One event was missing.

Try updating to 1.13.2

**Comment by daybrush** [comment]
1.13.2 => 1.13.3

**Comment by JonathanTreffler** [comment]
It works, thank you very much :)
