### ISSUE TITLE
hitRate: Can pixels be used instead of percentages

### ISSUE THREAD

**Issue by MingRock** [daybrush/selecto#61]
## Environments
* Framework name: React
* Framework version:
* Component name: 
* Component version:
* Testable Address(optional):

**Comment by daybrush** [comment]
@MingRock 


* `selecto` 1.14.0
* `react-selecto` 1.14.0
* `preact-selecto` 1.14.0
* `ngx-selecto` 1.14.0
* `svelte-selecto` 1.14.0
* `vue-selecto` 1.14.0
* `vue3-selecto` 1.0.0
* `lit-selecto` 1.14.0


selecto's new version is released. Check it again.

Use hitRate: "100px"
