### ISSUE TITLE
Versions 1.13.0 and later 'Container' and 'dragContainer' are invalid  

### ISSUE THREAD

**Issue by quliang945** [daybrush/selecto#62]
## Versions 1.13.0 and later 'Container' and 'dragContainer' are invalid  
* Unable to bind The default is body

**Comment by daybrush** [comment]
What do you mean?

Any detailed examples or error messages?

**Comment by daybrush** [comment]
@quliang945 

it's maybe similar to this issue: https://github.com/daybrush/selecto/issues/64
