### ISSUE TITLE
Vue 3 Support?

### ISSUE THREAD

**Issue by musiwei** [daybrush/selecto#70]
Thanks for the great plugin. 

Since Vue 3 has become the default version. When can we support it? 

Thanks for your time.

**Comment by daybrush** [comment]
@musiwei 

Ok. I'll support Vue 3

**Comment by daybrush** [comment]
@musiwei 


* `selecto` 1.14.0
* `react-selecto` 1.14.0
* `preact-selecto` 1.14.0
* `ngx-selecto` 1.14.0
* `svelte-selecto` 1.14.0
* `vue-selecto` 1.14.0
* `vue3-selecto` 1.0.0
* `lit-selecto` 1.14.0


selecto's new version is released. Check it again.
