### ISSUE TITLE
SelectoOptions should have optional properties, not just Union types with null

### ISSUE THREAD

**Issue by jrmoynihan** [daybrush/selecto#71]
## Environments
* Framework name: Svelte (Kit)
* Framework version: 1.0.0-next.287 
* Component name: Svelte-Selecto
* Component version: 1.13.2

## Description
When adding a `<Selecto>` component, the Typescript compiler [correctly] identifies if you haven't passed in _all_ of the SelectoOptions as parameters to the component:
![image](https://user-images.githubusercontent.com/65916939/155868576-99672a9e-1c78-4ed5-ac1d-341efc5919d8.png)

This is because the interface for SelectoOptions defines all of the props as required ones.  However, most of these are not required, so they should instead be declared as optional properties.  I'm not sure exactly which ones _must_ be included for the component to work, but I assume anything that could be `null` in its union type is optional and should be marked as such in the interface (see: below), and no errors should be thrown by not passing them into the component.  My guess is that even more of these could be set to optional.

Admittedly, I could just pass in a bunch of null parameters to the component to avoid this error, but that is far more tedious than the compiler knowing ahead of time which params are actually required.

```ts
// An example of the quick/easy changes that will prevent this error from showing up unnecessarily
// Note the question marks denoting optional props on the interface:
export interface SelectoOptions {
    target?: HTMLElement | null;
    container?: HTMLElement | null;
    rootContainer?: HTMLElement | null;
    dragContainer: Element | Window | Element[] | string;
    selectableTargets: Array<HTMLElement | string>;
    selectByClick: boolean;
    selectFromInside: boolean;
    continueSelect: boolean;
    toggleContinueSelect?: string[][] | string[] | string | null;
    keyContainer?: Document | HTMLElement | Window | null;
    hitRate: number;
    boundContainer?: BoundContainer | boolean | HTMLElement | string | null;
    scrollOptions: DragScrollOptions;
    checkInput: boolean;
    preventDefault: boolean;
    preventDragFromInside: boolean;
    cspNonce: string;
    ratio: number;
    getElementRect: getElementRectFunction;
    dragCondition?: ((e: OnParentDragStart) => boolean) | null;
}
```
Conversely, you could just set the <Selecto> component to take in a Partial<SelectoOptions>, setting all props to optional.  I think this was the original intent, based on the JS documentation, but it doesn't appear to have made it in at the interface level; The Partial does show up in the constructor of the component's class when calling it from JS, however:
![image](https://user-images.githubusercontent.com/65916939/155869061-bfb104ca-17cb-4d2c-ae5b-1f7da3b37aee.png)

**Comment by daybrush** [comment]
@jrmoynihan 

Thank you :) I'll fix it soon.

**Comment by daybrush** [comment]
@jrmoynihan 

* `selecto` 1.14.0
* `react-selecto` 1.14.0
* `preact-selecto` 1.14.0
* `ngx-selecto` 1.14.0
* `svelte-selecto` 1.14.0
* `vue-selecto` 1.14.0
* `vue3-selecto` 1.14.0
* `lit-selecto` 1.14.0


selecto's new version is released. Check it again.

**Comment by jrmoynihan** [comment]
@daybrush Thanks, I'll check it out!
