### ISSUE TITLE
selectFromInside=false is not working in selecto@^1.14.0

### ISSUE THREAD

**Issue by na2793** [daybrush/selecto#74]
## Environments
* Framework name: React
* Framework version: 
* Component name: react-selecto
* Component version: 1.15.0
* Testable Address(optional): https://codesandbox.io/s/c6cu5y

## Description

![](https://i.imgur.com/S0uNgA2.gif)

`selectFromInside` option does not work properly after version 1.14.0. (1.14.0 and 1.15.0)
You can check it at the testable address.

This is a fork from the official example, just changing the values ​​of `selectFromInside` and `selectByClick` to false.
This works fine if you change the version of react-selecto to 1.13.2 in dependencies.

**Comment by epicari** [comment]
Is there any progress on this issue?

**Comment by na2793** [comment]
It works perfect!
Thank you for your effort.
