### ISSUE TITLE
continueSelect without deselection

### ISSUE THREAD

**Issue by na2793** [daybrush/selecto#77]
## Environments
* Framework name: React

## Description
I'm trying to prevent the selected item to be deselected when I press shift key and select it again.
Is there any way to make this work?
Thanks for your time.

**Comment by daybrush** [comment]
@na2793 

Use continueSelectWithoutDeselect option with continueSelect. Thank you :)

**Comment by na2793** [comment]
As always, thank you!

**Comment by na2793** [comment]
![](https://i.imgur.com/U44AorV.png)
![](https://i.imgur.com/xZoEMMS.png)

I think `continueSelectWithoutDeselect` is always considered false.
It seems to be overridden in the Selecto class' constructor because it wasn't passed in.
Please review this issue.

**Comment by daybrush** [comment]
@na2793 

That way it probably won't be set to true.
Set `continueSelectorWithoutDeselect={true}`

**Comment by na2793** [comment]
I think my lint settings are confusing you. `={true}` is omitted, but it does exist.
Even if you write `={true}`, the result is the same.

**Comment by na2793** [comment]
https://codesandbox.io/s/naughty-hofstadter-dm877d

This is just a fork from the official example, only adding `continueSelectorWithoutDeselect={true}`.
Checking this out might help.

**Comment by daybrush** [comment]
@na2793 

oh thank you A bug was confirmed. I will release it again tomorrow.

**Comment by daybrush** [comment]
@na2793 

Test 1.16.2 version. Thank you :)

**Comment by na2793** [comment]
It works now.
Thank you for your effort!
