### ISSUE TITLE
after selecting multi elements and start dragging all elements collapse on each other at same place 

### ISSUE THREAD

**Issue by Nazakatalikharal** [daybrush/selecto#8]
## Environments
* Framework name: ReactJS
* Framework version: 16.13.1
* Component name: react-selecto + react-moveable
* Component version: react-selecto= 1.5.2 and react-moveable=0.21.6-rc 
* Video Address(optional): https://www.screencast.com/t/DIWtY7mpm6

## Description
after selecting group elements and start dragging all elements collapse on same position but if i start scalling after selecting elements than selected elements don't collapse then dragging also work perfectly.
![scale](https://user-images.githubusercontent.com/54443270/88759163-92adb500-d183-11ea-942b-ae635e100773.png)

**Comment by abdulbasit010** [comment]
I am also facing same issue with **react-selecto** and **react-moveable**.

**Comment by daybrush** [comment]
@Nazakatalikharal @abdulbasit010 

Would you show me the moveable code?

**Comment by Nazakatalikharal** [comment]
Issue was in logic , problem was in setting frame but now it work perfectly, Thanks for your support and contributions...

**Comment by xueerli** [comment]
@daybrush 
If i used isMoveableElement to stop, i can't choose the element when it is in a group.
Like this.This is what i expected.
![demo](https://ftp.bmp.ovh/imgs/2020/11/e4ad54229d400871.gif)

**Comment by daybrush** [comment]
@xueerli 

If you stop at onDragStart of selecto, selection is not possible.

Use moveable's onClickGroup event

https://codesandbox.io/s/tender-moon-6rc3i?file=/src/App.tsx

**Comment by xueerli** [comment]
I got it, thanks.
