### ISSUE TITLE
Selecto works slowly for large amount of data

### ISSUE THREAD

**Issue by robz95** [daybrush/selecto#81]
## Environments
* Framework name: vue
* Framework version: 2.6
* Component name: app.vue
* Testable Address: https://codesandbox.io/s/selecto-test-7d3e9v?file=/src/App.vue

## Description

Hello,

I need to add feature to select table cells in a table which contains a lot of records, usually ~12 000 (e.g. 120 columns, 100 rows).
I tried using your package, it works correctly, but it is not fast enough for this amount of data. I prepared sample sandbox which I linked above. It contains table, where you can select cells in the table body.

Do you know of any way to optimize the solution and to make it faster, so that it works smoothly for this amount of data?

**Comment by daybrush** [comment]
@robz95 

okay. I'll check it.

**Comment by daybrush** [comment]
@robz95 

* `selecto` 1.17.0
* `react-selecto` 1.17.0
* `preact-selecto` 1.17.0
* `ngx-selecto` 1.17.0
* `svelte-selecto` 1.17.0
* `vue-selecto` 1.17.0
* `vue3-selecto` 1.17.0
* `lit-selecto` 1.17.0


seelcto's new version is released. Check it again.
