### ISSUE TITLE
onClick event cannot prevent bubbling

### ISSUE THREAD

**Issue by h1530687053** [daybrush/selecto#89]
## Environments
The components are the latest version

## Description
Hello, author. When I used this component, I found that onclick and onmouseup did not trigger. Is there any good solution? 

My real goal is to stop bubbling after the mouse is down.

**Comment by daybrush** [comment]
@h1530687053 

* `lit-selecto` 1.18.0
* `preact-selecto` 1.15.0
* `react-selecto` 1.18.0
* `selecto` 1.18.0
* `svelte-selecto` 1.18.0
* `vue-selecto` 1.18.0
* `vue3-selecto` 1.4.0
* `ngx-selecto` 1.18.0


selecto's new version is released.

You can use `preventClickEventOnDragStart` or `preventClickEventOnDrag`
```ts
    // Prevent click event on drag. (mousemove, touchmove)
    preventClickEventOnDrag?: boolean;
    // Prevent click event on dragStart. (mousedown, touchstart)
    preventClickEventOnDragStart?: boolean;
```

**Comment by h1530687053** [comment]
Excellent，It works perfect!
Thank you for your effort.
