### ISSUE TITLE
Please support keyboard based selection as well

### ISSUE THREAD

**Issue by kotpal** [daybrush/selecto#9]
## Environments
* Framework name:
* Framework version:
* Component name: 
* Component version:
* Testable Address(optional):

**Comment by daybrush** [comment]
@kotpal 

Please explain in detail.

**Comment by kotpal** [comment]
I use keyboard a lot due to RSI using the mouse-pad or an external mouse. When I tabbed on the demo site, the gray boxes under 'Select anything' don't get keyboard focus - and hence I can't seem to be able to select them using the keyboard. I am forced to use the mouse or touch - which I tried with my mouse pad, but I couldn't select.

**Comment by daybrush** [comment]
@kotpal 

maybe check focus
```js
<Moveable onDragStart={e => {
    if (!document.hasFocus()) {
       return false;
         // e.stop(); <- not in react
    }
}
```
