### ISSUE TITLE
i need select when right click, like window desktop icons

### ISSUE THREAD

**Issue by WangJM001** [daybrush/selecto#90]
## Environments
* Framework name: React
* Framework version: 17.x
* Component name: Selecto
* Component version:1.17.0
* Testable Address(optional): 

## Description
1、when right click on noselect element, cancle other selected and select current element
2、when right click on selected element,  nothink happen

like window desktop icons

Thanks !

**Comment by daybrush** [comment]
@WangJM001 

okay. I'll consider it.

**Comment by daybrush** [comment]
@WangJM001 

* `lit-selecto` 1.18.0
* `preact-selecto` 1.15.0
* `react-selecto` 1.18.0
* `selecto` 1.18.0
* `svelte-selecto` 1.18.0
* `vue-selecto` 1.18.0
* `vue3-selecto` 1.4.0
* `ngx-selecto` 1.18.0


It seems that it was transpiled incorrectly while building. The new version doesn't seem to have any problems.

**Comment by daybrush** [comment]
@WangJM001 


* `lit-selecto` 1.18.0
* `preact-selecto` 1.15.0
* `react-selecto` 1.18.0
* `selecto` 1.18.0
* `svelte-selecto` 1.18.0
* `vue-selecto` 1.18.0
* `vue3-selecto` 1.4.0
* `ngx-selecto` 1.18.0


selecto's new version is released.

`preventRightClick` prop is added.

Set `preventRightClick` to false (default: true)

If set to false, you can also click/drag with the right button.

**Comment by WangJM001** [comment]
Thanks
