### ISSUE TITLE
movable / selecto 동시 사용시 container 확장 질문

### ISSUE THREAD

**Issue by 0hhanum** [daybrush/selecto#93]
## Environments
* Framework name: vue.js / moveable / selecto
* Framework version:  vue2 / 0.24.6 / 1.11.1 

## Description

안녕하세요. 

moveable / selecto 감사히 사용하고 있습니다.

한글 질문도 받아주시는지 모르겠네요

movable / selecto 를 동시에 사용중인데, 

[DEMO](https://daybrush.com/selecto/storybook/?path=/story/selecto-with-moveable--select-moveable-targets-in-real-time)

**해당 데모에서는 moveable 컴포넌트를 컨테이나 외부로 이동해도 컨테이너가 확장되지 않습니다.**

**진행중인 프로젝트에서는 컴포넌트를 옮기는 대로 컨테이너가 무한 확장해 스크롤이 생성됩니다.**

이를 방지하려고 하는데, 

데모 코드와 다른점을 찾지 못해 질문드립니다. 

프로젝트 중간에 투입되어 전체 소스를 파악하지 못하고 있는  상황이라,

컨테이너 확장 문제가 moveable / selecto API 로 설정이 가능한 부분일지 

혹은 다른 부분에서 해결해야 하는 부분일지 알려주시면 감사하겠습니다.

**Comment by daybrush** [comment]
@0hhanum

안녕하세요. selecto는 기본적으로 position: fixed이기 때문에 스크롤이 발생하지 않습니다. 스크롤이 발생했다는건
position: absolute로 되었기 때문이라고 추측이 되는데 부모나 그 상위에 transform이 적용되어 있지 않을까요?

적용되어있다면 transform이 적용되지 않은 컨테이너로 이동하는 것을 추천드립니다. 그렇다면 position: fixed로 돌아올겁니다.
적용이 되어있지만 바깥으로 빼는 것이 불가피하다 싶으면 boundContainer를 사용해 보시길 바랍니다.

적용이 되어있지 않은데 스크롤이 발생한다면 다시 한 번 더 댓글을 남겨주시길 바랍니다.

감사합니다.

**Comment by 0hhanum** [comment]
감사합니다!
