### ISSUE TITLE
Phantom mouse down with selectFromInside

### ISSUE THREAD

**Issue by adela-almasan** [daybrush/selecto#99]
## Environments
* Framework name: React
* Framework version: 17.0.2
* Component name: Selecto (+Moveable)
* Component version: 1.17.0

## Description

https://user-images.githubusercontent.com/88068998/187331828-2fd3effe-69aa-4ff6-a47c-3194b4787cf2.mov

Hi! I'm using Selecto with `selectFromInside` disabled and since I disabled the option, it seems to have created a phantom mouse down issue, which can become an annoyance very quickly. I cannot replicate it on none of the sandboxes online and I was wondering if you might have an idea what could be the issue in this case.

^ Attached you can find a screencast of the issue - I'm never holding down the mouse for a proper drag, the elements are just following my mouse.

```
this.selecto = new Selecto({
   container: this.div,
   rootContainer: this.div,
   selectableTargets: targetElements,
   toggleContinueSelect: 'shift',
   selectFromInside: false,
});
```

**Comment by daybrush** [comment]
@adela-almasan 

I'll fix it soon.

**Comment by daybrush** [comment]
@adela-almasan 
selecto's new version is released.  `data` event property is added.

The dragEnd event occurs earlier than when the moveable.dragStart method is called. If so, block dragStart like this:
```js
.on("selectEnd", e => {
        if (e.isDragStart) {
            e.inputEvent.preventDefault();

            e.data.timer = setTimeout(() => {
                moveable.dragStart(e.inputEvent);
            }, 100);
        }
    }).on("dragEnd", e => {
        clearTimeout(e.data.timer);
    })
```

**Comment by adela-almasan** [comment]
@daybrush That's perfect, thank you!

**Comment by adela-almasan** [comment]
@daybrush After upgrading I'm having some issues with `clickTarget` in the existing code - `selecto.clickTarget(event, div)`, attached you can find the console output. Would appreciate your input. Thank you!

![Screen Shot 2022-08-31 at 9 29 58 PM](https://user-images.githubusercontent.com/88068998/187820114-7ae7856d-7009-4d00-8478-ee00972621bb.png)

![Screen Shot 2022-08-31 at 9 31 27 PM](https://user-images.githubusercontent.com/88068998/187820123-7d4fb224-deb1-467f-80fa-2c317ea8f79a.png)

**Comment by daybrush** [comment]
@adela-almasan 

@winjeysong 

selecto's new version is released. Check it again.
